// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Karta.Model;

#nullable disable

namespace Karta.Migrations
{
    [DbContext(typeof(KartaContext))]
    [Migration("20230521175050_InitialDatabase3")]
    partial class InitialDatabase3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RPPP_WebApp.Model.Autocesta", b =>
                {
                    b.Property<int>("IdAutocesta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAutocesta"));

                    b.Property<int>("IdKoncesionar")
                        .HasColumnType("integer");

                    b.Property<string>("NazivAutocesta")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("character varying(5)");

                    b.HasKey("IdAutocesta");

                    b.HasIndex("IdKoncesionar");

                    b.ToTable("Autocesta");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Cjenik", b =>
                {
                    b.Property<int>("IdCjenik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCjenik"));

                    b.Property<decimal?>("IakategorijaCijenaEuro")
                        .IsRequired()
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("IakategorijaCijenaEuro");

                    b.Property<int>("IdNaplatnaPostaja")
                        .HasColumnType("integer");

                    b.Property<decimal?>("IiikategorijaCijenaEuro")
                        .IsRequired()
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("IiikategorijaCijenaEuro");

                    b.Property<decimal?>("IikategorijaCijenaEuro")
                        .IsRequired()
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("IikategorijaCijenaEuro");

                    b.Property<decimal?>("IkategorijaCijenaEuro")
                        .IsRequired()
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("IkategorijaCijenaEuro");

                    b.Property<decimal?>("IvkategorijaCijenaEuro")
                        .IsRequired()
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("IvkategorijaCijenaEuro");

                    b.Property<string>("IzlaznaPostaja")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.HasKey("IdCjenik");

                    b.HasIndex("IdNaplatnaPostaja");

                    b.ToTable("Cjenik");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Dionica", b =>
                {
                    b.Property<int>("IdDionica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDionica"));

                    b.Property<int>("BrojTraka")
                        .HasColumnType("integer");

                    b.Property<int>("IdAutocesta")
                        .HasColumnType("integer");

                    b.Property<decimal>("Kilometraža")
                        .HasColumnType("numeric(10, 3)");

                    b.Property<string>("NazivDionica")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("character varying(120)");

                    b.HasKey("IdDionica");

                    b.HasIndex("IdAutocesta");

                    b.ToTable("Dionica");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Dogadaj", b =>
                {
                    b.Property<int>("IdDogadaj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdDogadaj");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDogadaj"));

                    b.Property<string>("Coordinates")
                        .HasColumnType("text")
                        .HasColumnName("Coordinates");

                    b.Property<int>("IdDionica")
                        .HasColumnType("integer")
                        .HasColumnName("IdDionica");

                    b.Property<string>("MeteoroloskiUvjeti")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("MeteoroloskiUvjeti");

                    b.Property<string>("OpisDogadaja")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("OpisDogadaja");

                    b.Property<DateTime?>("VrijemeDogadaja")
                        .IsRequired()
                        .HasColumnType("datetime")
                        .HasColumnName("VrijemeDogadaja");

                    b.HasKey("IdDogadaj");

                    b.HasIndex("IdDionica");

                    b.ToTable("Dogadaj");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Encprolazak", b =>
                {
                    b.Property<int>("IdProlaska")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProlaska"));

                    b.Property<int>("IdEnc")
                        .HasColumnType("integer")
                        .HasColumnName("IdENC");

                    b.Property<int>("IdNaplatnaKucica")
                        .HasColumnType("integer");

                    b.Property<string>("KategorijaVozila")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("VrijemeProlaska")
                        .HasColumnType("datetime");

                    b.HasKey("IdProlaska");

                    b.HasIndex("IdEnc");

                    b.HasIndex("IdNaplatnaKucica");

                    b.HasIndex(new[] { "VrijemeProlaska", "IdNaplatnaKucica" }, "Index_")
                        .IsUnique();

                    b.HasIndex(new[] { "VrijemeProlaska", "IdEnc" }, "Index_vrijemeVozilo")
                        .IsUnique();

                    b.ToTable("ENCProlazak", (string)null);
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Encuredaj", b =>
                {
                    b.Property<int>("IdEnc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdENC");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEnc"));

                    b.Property<string>("BrojRacuna")
                        .IsRequired()
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("character(14)")
                        .IsFixedLength();

                    b.Property<string>("EmailVlasnika")
                        .IsRequired()
                        .HasMaxLength(320)
                        .IsUnicode(false)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ImeVlasnika")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PrezimeVlasnika")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("StanjeNaRacunuEuro")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<DateTime>("VrijediOd")
                        .HasColumnType("date");

                    b.HasKey("IdEnc")
                        .HasName("PK__tmp_ms_x__0F3CDA59D3292AFD");

                    b.HasIndex(new[] { "EmailVlasnika" }, "UQ__tmp_ms_x__41822FC0EADFFB03")
                        .IsUnique();

                    b.HasIndex(new[] { "EmailVlasnika" }, "email_unique")
                        .IsUnique();

                    b.HasIndex(new[] { "BrojRacuna" }, "racun_unique")
                        .IsUnique();

                    b.ToTable("ENCUredaj", (string)null);
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Koncesionar", b =>
                {
                    b.Property<int>("IdKoncesionar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdKoncesionar"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Fax")
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("NazivKoncesionar")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NazivMjesto")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Oibkoncesionar")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("OIBKoncesionar");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("TipKoncesionar")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("WebUrl")
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("WebURL");

                    b.HasKey("IdKoncesionar");

                    b.ToTable("Koncesionar");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.NaplatnaKucica", b =>
                {
                    b.Property<int>("IdNaplatnaKucica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNaplatnaKucica"));

                    b.Property<int>("BrojStaze")
                        .HasColumnType("integer");

                    b.Property<int>("IdNaplatnaPostaja")
                        .HasColumnType("integer");

                    b.Property<string>("MaxKategorijaVozila")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("MinKategorijaVozila")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("NadoplataEnca")
                        .HasColumnType("text")
                        .HasColumnName("NadoplataENCa");

                    b.Property<string>("OtvorenaNaplatnaKucica")
                        .HasColumnType("text");

                    b.Property<string>("PodrzavaEnc")
                        .HasColumnType("text")
                        .HasColumnName("PodrzavaENC");

                    b.HasKey("IdNaplatnaKucica");

                    b.HasIndex(new[] { "IdNaplatnaPostaja", "BrojStaze" }, "index_naplatnaKucicaStazaUnique")
                        .IsUnique();

                    b.ToTable("NaplatnaKucica");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.NaplatnaPostaja", b =>
                {
                    b.Property<int>("IdNaplatnaPostaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNaplatnaPostaja"));

                    b.Property<int>("IdAutocesta")
                        .HasColumnType("integer")
                        .HasColumnName("IdAutocesta");

                    b.Property<string>("Kontakt")
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NaplatnaPostajaKoordinateEw")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("NaplatnaPostajaKoordinateEw");

                    b.Property<string>("NaplatnaPostajaKoordinateNs")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("NaplatnaPostajaKoordinateNs");

                    b.Property<string>("NazivNaplatnaPostaja")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.HasKey("IdNaplatnaPostaja");

                    b.HasIndex("IdAutocesta");

                    b.ToTable("NaplatnaPostaja");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Objekt", b =>
                {
                    b.Property<int>("IdObjekt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdObjekt"));

                    b.Property<int?>("Duljina")
                        .HasColumnType("integer");

                    b.Property<int>("IdDionica")
                        .HasColumnType("integer");

                    b.Property<int?>("NadmorskaVisina")
                        .HasColumnType("integer");

                    b.Property<string>("NazivObjekt")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ObjektKoordinateEw")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ObjektKoordinateEW");

                    b.Property<string>("ObjektKoordinateNs")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ObjektKoordinateNS");

                    b.Property<string>("Opis")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Podtip")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("Stacionaza")
                        .HasColumnType("numeric(10, 3)");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("character varying(8)");

                    b.HasKey("IdObjekt");

                    b.HasIndex("IdDionica");

                    b.ToTable("Objekt");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Odmoriste", b =>
                {
                    b.Property<int>("IdOdmoriste")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOdmoriste"));

                    b.Property<int>("IdAutocesta")
                        .HasColumnType("integer");

                    b.Property<string>("NazivOdmoriste")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("OdmoristeKoordinateEw")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("OdmoristeKoordinateEw");

                    b.Property<string>("OdmoristeKoordinateNs")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("OdmoristeKoordinateNs");

                    b.Property<string>("Smjer")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.HasKey("IdOdmoriste");

                    b.HasIndex("IdAutocesta");

                    b.ToTable("Odmoriste");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Odrzavanje", b =>
                {
                    b.Property<int>("IdOdržavanje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOdržavanje"));

                    b.Property<int>("IdObjekt")
                        .HasColumnType("integer");

                    b.Property<int>("IdVrstaOdrzavanja")
                        .HasColumnType("integer");

                    b.Property<string>("Izvodac")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("Vrijeme")
                        .HasColumnType("datetime");

                    b.HasKey("IdOdržavanje");

                    b.HasIndex("IdObjekt");

                    b.HasIndex("IdVrstaOdrzavanja");

                    b.ToTable("Odrzavanje");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Odziv", b =>
                {
                    b.Property<int>("IdOdziv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idOdziv");

                    b.Property<int>("IdDogadaj")
                        .HasColumnType("integer")
                        .HasColumnName("idDogadaj");

                    b.Property<int>("IdVrstaOdziva")
                        .HasColumnType("integer")
                        .HasColumnName("idVrstaOdziva");

                    b.Property<DateTime?>("VrijemeOdziva")
                        .HasColumnType("datetime")
                        .HasColumnName("vrijemeOdziva");

                    b.HasKey("IdOdziv");

                    b.ToTable("Odziv");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.PrateciSadrzaj", b =>
                {
                    b.Property<int>("IdPratecegSadrzaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPratecegSadrzaja"));

                    b.Property<int>("IdOdmoriste")
                        .HasColumnType("integer");

                    b.Property<int>("IdVrstaPratecegSadrzaja")
                        .HasColumnType("integer");

                    b.Property<string>("NazivPratecegSadrzaja")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("character varying(120)");

                    b.Property<TimeSpan?>("RadnoVrijemeDo")
                        .IsRequired()
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("RadnoVrijemeOd")
                        .IsRequired()
                        .HasColumnType("interval");

                    b.HasKey("IdPratecegSadrzaja");

                    b.HasIndex("IdOdmoriste");

                    b.HasIndex("IdVrstaPratecegSadrzaja");

                    b.ToTable("PrateciSadrzaj");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.VrstaOdrzavanja", b =>
                {
                    b.Property<int>("IdVrsta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVrsta"));

                    b.Property<string>("NazivVrsta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdVrsta");

                    b.ToTable("VrstaOdrzavanja");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.VrstaOdziva", b =>
                {
                    b.Property<int>("IdVrstaOdziva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idVrstaOdziva");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVrstaOdziva"));

                    b.Property<string>("ImeOdziva")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("imeOdziva");

                    b.Property<string>("OpisOdziva")
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("opisOdziva");

                    b.HasKey("IdVrstaOdziva");

                    b.ToTable("VrstaOdziva");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.VrstaPratecegSadrzaj", b =>
                {
                    b.Property<int>("IdVrstaPratecegSadrzaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVrstaPratecegSadrzaja"));

                    b.Property<string>("NazivVrstePratecegSadrzaja")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("character varying(120)");

                    b.HasKey("IdVrstaPratecegSadrzaja")
                        .HasName("PK_VrstaPratecegSadrzaja");

                    b.HasIndex(new[] { "NazivVrstePratecegSadrzaja" }, "UNIQUE_NazivVrstePratecegSadrzaja")
                        .IsUnique();

                    b.ToTable("VrstaPratecegSadrzaj");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Autocesta", b =>
                {
                    b.HasOne("RPPP_WebApp.Model.Koncesionar", "IdKoncesionarNavigation")
                        .WithMany("Autocesta")
                        .HasForeignKey("IdKoncesionar")
                        .IsRequired()
                        .HasConstraintName("Autocesta_IdKoncesionar_fkey");

                    b.Navigation("IdKoncesionarNavigation");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Cjenik", b =>
                {
                    b.HasOne("RPPP_WebApp.Model.NaplatnaPostaja", "IdNaplatnaPostajaNavigation")
                        .WithMany("Cjenik")
                        .HasForeignKey("IdNaplatnaPostaja")
                        .IsRequired()
                        .HasConstraintName("Cjenik_IdNaplatnaPostaja_fkey");

                    b.Navigation("IdNaplatnaPostajaNavigation");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Dionica", b =>
                {
                    b.HasOne("RPPP_WebApp.Model.Autocesta", "IdAutocestaNavigation")
                        .WithMany("Dionica")
                        .HasForeignKey("IdAutocesta")
                        .IsRequired()
                        .HasConstraintName("Dionica_IdAutocesta_fkey");

                    b.Navigation("IdAutocestaNavigation");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Dogadaj", b =>
                {
                    b.HasOne("RPPP_WebApp.Model.Dionica", "IdDionicaNavigation")
                        .WithMany("Dogadaj")
                        .HasForeignKey("IdDionica")
                        .IsRequired()
                        .HasConstraintName("Dogadaj_IdDionica_fkey");

                    b.Navigation("IdDionicaNavigation");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Encprolazak", b =>
                {
                    b.HasOne("RPPP_WebApp.Model.Encuredaj", "IdEncNavigation")
                        .WithMany("Encprolazak")
                        .HasForeignKey("IdEnc")
                        .IsRequired()
                        .HasConstraintName("FK_ENC");

                    b.HasOne("RPPP_WebApp.Model.NaplatnaKucica", "IdNaplatnaKucicaNavigation")
                        .WithMany("Encprolazak")
                        .HasForeignKey("IdNaplatnaKucica")
                        .IsRequired()
                        .HasConstraintName("FK_Kucica");

                    b.Navigation("IdEncNavigation");

                    b.Navigation("IdNaplatnaKucicaNavigation");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.NaplatnaKucica", b =>
                {
                    b.HasOne("RPPP_WebApp.Model.NaplatnaPostaja", "IdNaplatnaPostajaNavigation")
                        .WithMany("NaplatnaKucica")
                        .HasForeignKey("IdNaplatnaPostaja")
                        .IsRequired()
                        .HasConstraintName("FK_NaplatnaKucica_NaplatnaPostaja");

                    b.Navigation("IdNaplatnaPostajaNavigation");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.NaplatnaPostaja", b =>
                {
                    b.HasOne("RPPP_WebApp.Model.Autocesta", "IdAutocestaNavigation")
                        .WithMany("NaplatnaPostaja")
                        .HasForeignKey("IdAutocesta")
                        .IsRequired()
                        .HasConstraintName("naplatnapostaja_idautocesta_fkey");

                    b.Navigation("IdAutocestaNavigation");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Objekt", b =>
                {
                    b.HasOne("RPPP_WebApp.Model.Dionica", "IdDionicaNavigation")
                        .WithMany("Objekt")
                        .HasForeignKey("IdDionica")
                        .IsRequired()
                        .HasConstraintName("FK_Objekt_Dionica");

                    b.Navigation("IdDionicaNavigation");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Odmoriste", b =>
                {
                    b.HasOne("RPPP_WebApp.Model.Autocesta", "IdAutocestaNavigation")
                        .WithMany("Odmoriste")
                        .HasForeignKey("IdAutocesta")
                        .IsRequired()
                        .HasConstraintName("odmoriste_idautocesta_fkey");

                    b.Navigation("IdAutocestaNavigation");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Odrzavanje", b =>
                {
                    b.HasOne("RPPP_WebApp.Model.Objekt", "IdObjektNavigation")
                        .WithMany("Odrzavanje")
                        .HasForeignKey("IdObjekt")
                        .IsRequired()
                        .HasConstraintName("FK_Odrzavanje_Objekt");

                    b.HasOne("RPPP_WebApp.Model.VrstaOdrzavanja", "IdVrstaOdrzavanjaNavigation")
                        .WithMany("Odrzavanje")
                        .HasForeignKey("IdVrstaOdrzavanja")
                        .IsRequired()
                        .HasConstraintName("FK_Odrzavanje_VrstaOdrzavanja");

                    b.Navigation("IdObjektNavigation");

                    b.Navigation("IdVrstaOdrzavanjaNavigation");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Odziv", b =>
                {
                    b.HasOne("RPPP_WebApp.Model.Dogadaj", "IdOdzivNavigation")
                        .WithOne("Odziv")
                        .HasForeignKey("RPPP_WebApp.Model.Odziv", "IdOdziv")
                        .IsRequired()
                        .HasConstraintName("fk_odzivDogadaj");

                    b.HasOne("RPPP_WebApp.Model.VrstaOdziva", "IdOdziv1")
                        .WithOne("Odziv")
                        .HasForeignKey("RPPP_WebApp.Model.Odziv", "IdOdziv")
                        .IsRequired()
                        .HasConstraintName("fk_odzivVrstaOdziva");

                    b.Navigation("IdOdziv1");

                    b.Navigation("IdOdzivNavigation");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.PrateciSadrzaj", b =>
                {
                    b.HasOne("RPPP_WebApp.Model.Odmoriste", "IdOdmoristeNavigation")
                        .WithMany("PrateciSadrzaj")
                        .HasForeignKey("IdOdmoriste")
                        .IsRequired()
                        .HasConstraintName("pratecisadrzaj_idodmoriste_fkey");

                    b.HasOne("RPPP_WebApp.Model.VrstaPratecegSadrzaj", "IdVrstaPratecegSadrzajaNavigation")
                        .WithMany("PrateciSadrzaj")
                        .HasForeignKey("IdVrstaPratecegSadrzaja")
                        .IsRequired()
                        .HasConstraintName("pratecisadrzaj_idvrstapratecegsadrzaja_fkey");

                    b.Navigation("IdOdmoristeNavigation");

                    b.Navigation("IdVrstaPratecegSadrzajaNavigation");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Autocesta", b =>
                {
                    b.Navigation("Dionica");

                    b.Navigation("NaplatnaPostaja");

                    b.Navigation("Odmoriste");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Dionica", b =>
                {
                    b.Navigation("Dogadaj");

                    b.Navigation("Objekt");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Dogadaj", b =>
                {
                    b.Navigation("Odziv");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Encuredaj", b =>
                {
                    b.Navigation("Encprolazak");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Koncesionar", b =>
                {
                    b.Navigation("Autocesta");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.NaplatnaKucica", b =>
                {
                    b.Navigation("Encprolazak");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.NaplatnaPostaja", b =>
                {
                    b.Navigation("Cjenik");

                    b.Navigation("NaplatnaKucica");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Objekt", b =>
                {
                    b.Navigation("Odrzavanje");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.Odmoriste", b =>
                {
                    b.Navigation("PrateciSadrzaj");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.VrstaOdrzavanja", b =>
                {
                    b.Navigation("Odrzavanje");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.VrstaOdziva", b =>
                {
                    b.Navigation("Odziv");
                });

            modelBuilder.Entity("RPPP_WebApp.Model.VrstaPratecegSadrzaj", b =>
                {
                    b.Navigation("PrateciSadrzaj");
                });
#pragma warning restore 612, 618
        }
    }
}
